name: Create Projector MPS Instance

on:
  pull_request_target:
    types: [synchronize, opened, reopened]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest

    env:
      # only works on pull_request events
      REPO_NAME: ${{ github.event.repository.name }}

    steps:
      - name:  Extract Branch Name
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_HEAD_REF})"
        id: extract_branch

      - name: Calc Port Number
        run: echo "##[set-output name=port;]$(echo $((4000 + ${{github.event.number}})))"
        id: extract_port

      - name: Print github PR Info
        run: echo branch $BRANCH_NAME PORTR_NUMBER ${{ steps.extract_port.outputs.port }} REPO_NAME ${{env.REPO_NAME }}
      - name: execute ssh command
        uses: fifsky/ssh-action@v0.0.6
        with:
          command: |
            docker run --name ${{ steps.extract_branch.outputs.branch }} -d -p ${{ steps.extract_port.outputs.port }}:8887 projectormps/projector-mps:2020.3  ${{ steps.extract_branch.outputs.branch }}  https://github.com/arimer/projector-mps-rcp-demo.git
            docker ps
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER_NAME }}
          key: ${{ secrets.GHA_KEY }}
      - uses: coolya/action-pr-link@v1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          modelix-url: "http://51.15.137.138:${{ steps.extract_port.outputs.port }}"