name: Shutdown Projector MPS Instance

on:
  pull_request:
    types: [closed]

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest

    steps:
      - name: Extract Branch Name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

            # extract branch name on pull request
      - name: Extract Branch Name on PR
        if: github.event_name == 'pull_request'
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_HEAD_REF})"

      - name: execute ssh command
        uses: fifsky/ssh-action@v0.0.6
        with:
          command: |
            docker stop $BRANCH_NAME
            docker rm $BRANCH_NAME
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER_NAME }}
          key: ${{ secrets.GHA_KEY }}